### ISSUE TITLE
Unable to find the parameter demo code as per video

### ISSUE THREAD

**Issue by Jackogip** [micro-ROS/micro_ros_renesas_demos#125]
## Issue template

- Hardware description: Custom board
- RTOS: Bare Metal
- Installation type: e2studio
- Version or commit hash: Humble

Is the parameter demo code available as shown in the demo video here: [link](https://www.youtube.com/watch?v=_FRAoU1uFwk&list=PL-Kh3H15FsNTD8A8wD0_iMnvhDsqw-rga&index=13)

I'm currently trying to set up a parameter server but I'm running into BSP_CFG_HANDLE_UNRECOVERABLE_ERROR(0); so having the actual demo code would get good to compare to.

**Comment by Jackogip** [comment]
An update on not being able to set up a parameter server.

I found that I was running into a heap size limit. This was with only 1x node, 1x publisher, and 1x parameter setup.

By either increasing the heap allocation or setting the `param_options` to `low_mem_mode=true `seemed to have solved the issue for me.

Was there a reason for recommending a heap and main stack size of 5000bytes - here: [link](https://github.com/micro-ROS/micro_ros_renesas2estudio_component#integrating-micro-ros-in-your-project)?

**Comment by Acuadros95** [comment]
The parameter server is quite heavy. We included a low memory mode configuration that you can also try out, check this documentation: [Parameter Server API](https://docs.vulcanexus.org/en/latest/rst/microros_documentation/user_api/user_api_parameter_server.html).

> Was there a reason for recommending a heap and main stack size of 5000bytes - here: [link](https://github.com/micro-ROS/micro_ros_renesas2estudio_component#integrating-micro-ros-in-your-project)?

Its a generic configuration to fit basic micro-ROS applications, feel free to adapt the memory configuration to your needs.

Closing as the problem was solved on your side.
